### PR TITLE
add MassGemSender

### PR DESCRIPTION
**Pull request by michaelts1**
see https://github.com/michaelts1/MassGemSender

### CODE REVIEW

**Comment by edvordo** [comment]
Appreciate the PR. If you could:

 * include the functionality into the `const fn` and `cost VARIABLES` objects
 * use full function names (no `chkGems`)
 * use `===` or `!==`
 * extract css to the `resources/css/qol.css` file or where appropriate
 * fix code style (e.g.: indentation)
 * **most importantly:** add settings to toggle all of it without the need to refresh

Then I will consider merging :)

**Comment by michaelts1** [comment]
Hi, worked on the code a little more, can you please review the PR again?

**Comment by edvordo** [comment]
Seems like you pushed to your [master](https://github.com/michaelts1/roa-qol/tree/master) branch instead of the [patch-1](https://github.com/michaelts1/roa-qol/tree/patch-1) branch from which you made the pull request, ergo changes are not visible here.

From the commits in the master branch, I see that the whole UI change is not tiggleable without refresh if I'm not too much mistaken. This is a dealbreaker for me, sorry.

Also, it seems like that you forgot about hte css styles you had in this pull request :)

Other than that, looks good, I'll have to test the whole thing myself once the changes I requested are made.

**Comment by michaelts1** [comment]
pushed the changes to the right branch this time :)

I can enable and disable the UI without refreshing. only have to refresh one time to update the script, then refreshing is not needed to enable/disable the feature.

not sure what you mean by the css thing, but anyway thanks for taking the time to look through my messy code

**Comment by michaelts1** [comment]
No longer relevant as a good interface was implemented

**Pull request closed without merging**
